### ISSUE TITLE
Error installing pynput

### ISSUE THREAD

**Issue by stefanasandei** [michaelraduu/Keylogger#1]
![fghfg](https://user-images.githubusercontent.com/52822996/71553598-e9e77d80-2a1a-11ea-84a3-14ba2b7956e6.png)
![Untitled22](https://user-images.githubusercontent.com/52822996/71553599-eeac3180-2a1a-11ea-84d1-f1371bc63c8a.png)

In cmd, it shows me that pynput is _installed_, bui the IDE ca**n't** find it.
(sugest: `pip3 install pynput`, run cmd as root)
**Can you help me?**

**Comment by mihaicodes** [comment]
Dmed him in private, issue was he had python2 and python3 with pip installed and he needed to run pip3 not pip2
